targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - implicit_dynamic_parameter
            - cast_nullable_to_non_nullable
            - require_trailing_commas
      json_serializable:
        options:
          field_rename: snake
          checked: true
